const GAS_ENDPOINT = "https://script.google.com/macros/s/AKfycbx_jhrORToigZakIlBxbKX7EuBJOtBL2MDBXNmh5DapORvBSt7kZQK0QtxjswqjBdH9/exec";
const sampleProperties = [
{id:"001",published:true,status:"販売中",title:"交野市郡津 中古戸建",price:"1,680万円",address:"大阪府交野市郡津",station:"京阪交野線 郡津駅",walk:"徒歩8分",layout:"4LDK",land_area:"95.2㎡",building_area:"88.4㎡",year:"2002年築",image_url:"",description:"落ち着いた住宅街にある、家族で暮らしやすい中古戸建です。"},
{id:"002",published:true,status:"販売中",title:"枚方市藤阪 中古戸建",price:"2,480万円",address:"大阪府枚方市藤阪",station:"JR学研都市線 藤阪駅",walk:"徒歩12分",layout:"4LDK",land_area:"120.1㎡",building_area:"102.6㎡",year:"2015年築",image_url:"",description:"ゆとりある敷地と明るい室内が魅力の中古戸建です。"},
{id:"003",published:true,status:"成約済",title:"寝屋川市打上 中古戸建",price:"—",address:"大阪府寝屋川市打上",station:"JR学研都市線 寝屋川公園駅",walk:"徒歩10分",layout:"3LDK",land_area:"100.5㎡",building_area:"89.1㎡",year:"2010年築",image_url:"",description:"成約事例として掲載しているサンプル物件です。"}
];
function esc(v=""){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
function truthy(v){return v===true||String(v).toLowerCase()==="true"||String(v)==="1";}
function renderProperties(items,source){const grid=document.getElementById("propertyGrid"),status=document.getElementById("propertyStatus");const list=items.filter(i=>truthy(i.published));if(!list.length){status.textContent="現在公開中の物件はありません。";grid.innerHTML="";return;}status.textContent="";grid.innerHTML=list.map(i=>{const image=i.image_url?`<img src="${esc(i.image_url)}" alt="${esc(i.title)}" loading="lazy">`:`<div class="placeholder-house">🏠</div>`;return `<article class="property-card"><div class="property-image">${image}</div><div class="property-body"><div class="property-top"><span class="badge">${esc(i.status||"物件情報")}</span><span class="price">${esc(i.price||"価格未定")}</span></div><h3>${esc(i.title||"物件名未設定")}</h3><p class="meta">🚉 ${esc([i.station,i.walk].filter(Boolean).join(" "))}<br>▣ ${esc(i.layout||"")}<br>⌂ 土地 ${esc(i.land_area||"-")}　建物 ${esc(i.building_area||"-")}<br>▤ ${esc(i.year||"")}</p><p class="description">${esc(i.description||"")}</p></div></article>`}).join("");}
async function loadProperties(){if(!GAS_ENDPOINT){renderProperties(sampleProperties,"サンプルデータ");return;}try{const r=await fetch(`${GAS_ENDPOINT}?t=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();const items=Array.isArray(d)?d:d.properties;if(!Array.isArray(items))throw new Error("Unexpected response format");renderProperties(items,"Googleスプレッドシート");}catch(e){console.error(e);renderProperties(sampleProperties,"サンプルデータ");}}
document.getElementById("year").textContent=new Date().getFullYear();loadProperties();
